from __future__ import annotations

from pathlib import Path

from ace_lite.indexer import build_index
from ace_lite.retrieval_shared import CandidateSelectionResult
from ace_lite.plan_quick import build_plan_quick
from ace_lite.plan_quick import build_plan_quick_policy_observability
from ace_lite.plan_quick import score_plan_quick_rows
from ace_lite.repomap.ranking import rank_index_files


def _write_file(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def test_score_plan_quick_rows_rescores_and_sorts() -> None:
    rows = [
        {"path": "src/auth/token.py", "module": "auth.token", "language": "python", "score": 1.0},
        {"path": "src/auth/session.py", "module": "auth.session", "language": "python", "score": 3.0},
        {"path": "src/other.py", "module": "misc", "language": "python", "score": 10.0},
    ]

    scored = score_plan_quick_rows(query="auth token", rows=rows, lexical_boost_per_hit=5.0)

    assert [row.path for row in scored] == [
        "src/auth/token.py",  # 1.0 + 2 hits * 5.0 = 11.0
        "src/other.py",  # 10.0 + 0 = 10.0
        "src/auth/session.py",  # 3.0 + 1 * 5.0 = 8.0
    ]
    assert scored[0].lexical_hits == 2
    assert scored[0].fused_score == 11.0


def test_score_plan_quick_rows_tiebreaks_by_path() -> None:
    rows = [
        {"path": "b.py", "module": "", "language": "python", "score": 1.0},
        {"path": "a.py", "module": "", "language": "python", "score": 1.0},
    ]

    scored = score_plan_quick_rows(query="missing", rows=rows, lexical_boost_per_hit=5.0)

    assert [row.path for row in scored] == ["a.py", "b.py"]


def test_build_index_marks_generated_files(tmp_path: Path) -> None:
    _write_file(
        tmp_path / "pkg/contract/erc20_generated.py",
        "\n".join(
            [
                "# Code generated by abigen. DO NOT EDIT.",
                "",
                "def erc20_transfer():",
                "    return 1",
                "",
            ]
        ),
    )
    _write_file(
        tmp_path / "internal/app/api/shutdown/allowlist.py",
        "\n".join(
            [
                "def allowlist_enabled():",
                "    return True",
                "",
            ]
        ),
    )

    payload = build_index(tmp_path, languages=["python"])
    files = payload.get("files", {})
    assert isinstance(files, dict)
    assert files["pkg/contract/erc20_generated.py"]["generated"] is True
    assert files["internal/app/api/shutdown/allowlist.py"]["generated"] is False


def test_build_plan_quick_prefers_business_logic_over_generated(tmp_path: Path) -> None:
    business_symbols = "\n".join(
        [
            "def shutdown_middleware():\n    return True\n",
            "def allowlist_route():\n    return True\n",
            "def blocklist_route():\n    return True\n",
        ]
    )
    _write_file(
        tmp_path / "internal/app/api/shutdown/allowlist.py",
        business_symbols,
    )

    generated_symbols = "\n".join(
        [f"def generated_fn_{i}():\n    return {i}\n" for i in range(40)]
    )
    _write_file(
        tmp_path / "pkg/contract/erc20_generated.py",
        "\n".join(["# Code generated by tool. DO NOT EDIT.", "", generated_symbols]),
    )

    result = build_plan_quick(
        query="shutdown allowlist middleware",
        root=tmp_path,
        languages="python",
        top_k_files=5,
        repomap_top_k=24,
    )
    assert result["ranking_source"] == "ranker"
    assert result["candidate_ranker"] == "rrf_hybrid"
    assert isinstance(result.get("index_cache"), dict)
    assert result["candidate_files"]
    assert result["candidate_files"][0].endswith("internal/app/api/shutdown/allowlist.py")

    contract_query = build_plan_quick(
        query="erc20 contract binding",
        root=tmp_path,
        languages="python",
        top_k_files=5,
        repomap_top_k=24,
    )
    assert contract_query["candidate_files"]
    assert contract_query["candidate_files"][0].startswith("pkg/contract/")

    assert isinstance(contract_query.get("index_cache"), dict)
    assert contract_query["index_cache"].get("cache_hit") is True
    assert contract_query["index_cache"].get("mode") == "cache_only"

    assert result["candidate_files"] != contract_query["candidate_files"]


def test_build_plan_quick_repomap_expand_includes_stage_payload(tmp_path: Path) -> None:
    _write_file(tmp_path / "src/app.py", "def shutdown_middleware():\n    return True\n")
    _write_file(tmp_path / "src/other.py", "def helper():\n    return 1\n")

    result = build_plan_quick(
        query="shutdown middleware",
        root=tmp_path,
        languages="python",
        top_k_files=3,
        repomap_top_k=8,
        repomap_expand=True,
        repomap_neighbor_limit=10,
        repomap_neighbor_depth=1,
    )
    assert result["ranking_source"] == "ranker"
    assert isinstance(result.get("repomap_stage"), (dict, type(None)))
    # In tiny repos neighbor_paths may be empty, but stage payload should exist.
    assert isinstance(result.get("repomap_stage"), dict)
    assert isinstance(result["repomap_stage"].get("seed_paths"), list)
    assert isinstance(result["repomap_stage"].get("neighbor_paths"), list)


def test_build_plan_quick_candidate_ranker_option(tmp_path: Path) -> None:
    _write_file(tmp_path / "src/auth/token.py", "def token_auth():\n    return True\n")
    _write_file(tmp_path / "src/auth/session.py", "def session_auth():\n    return True\n")
    _write_file(tmp_path / "src/misc.py", "def other():\n    return 1\n")

    bm25 = build_plan_quick(
        query="auth token",
        root=tmp_path,
        languages="python",
        top_k_files=3,
        repomap_top_k=12,
        candidate_ranker="bm25_lite",
    )
    assert bm25["ranking_source"] == "ranker"
    assert bm25["candidate_ranker"] == "bm25_lite"
    assert bm25["candidate_files"]


def test_build_plan_quick_policy_observability_uses_shared_policy_resolution(
    monkeypatch,
) -> None:
    captured: dict[str, object] = {}

    def fake_resolve_retrieval_policy(**kwargs):
        captured.update(kwargs)
        return {
            "name": "doc_intent",
            "source": "auto",
            "version": "v1",
            "embedding_enabled": True,
            "docs_enabled": True,
            "repomap_enabled": True,
            "graph_lookup_enabled": False,
            "chunk_semantic_rerank_enabled": True,
            "semantic_rerank_time_budget_ms": 120,
        }

    monkeypatch.setattr(
        "ace_lite.plan_quick.resolve_retrieval_policy",
        fake_resolve_retrieval_policy,
    )

    profile, payload = build_plan_quick_policy_observability(
        query="how architecture works",
    )

    assert profile == "doc_intent"
    assert payload == {
        "requested": "auto",
        "selected": "doc_intent",
        "source": "auto",
        "version": "v1",
        "embedding_enabled": True,
        "docs_enabled": True,
        "repomap_enabled": True,
        "graph_lookup_enabled": False,
        "chunk_semantic_rerank_enabled": True,
        "semantic_rerank_time_budget_ms": 120,
    }
    assert captured == {
        "query": "how architecture works",
        "retrieval_policy": "auto",
        "policy_version": "v1",
        "cochange_enabled": True,
        "embedding_enabled": True,
    }


def test_build_plan_quick_uses_shared_candidate_selection(monkeypatch, tmp_path: Path) -> None:
    _write_file(tmp_path / "src/app.py", "def auth_token():\n    return True\n")
    captured: dict[str, object] = {}

    class FakeRuntimeProfile:
        top_k_files = 8

        def selection_kwargs(self, *, corpus_size: int) -> dict[str, object]:
            captured["corpus_size"] = corpus_size
            return {
                "candidate_ranker": "rrf_hybrid",
                "min_candidate_score": 1,
                "top_k_files": 8,
                "corpus_size": corpus_size,
                "hybrid_fusion_mode": "linear",
                "hybrid_rrf_k": 60,
                "hybrid_weights": {},
                "index_hash": None,
                "allow_empty_terms_fail_open": False,
            }

    def fake_build_retrieval_runtime_profile(**kwargs):
        captured["profile_kwargs"] = kwargs
        return FakeRuntimeProfile()

    monkeypatch.setattr(
        "ace_lite.plan_quick.build_retrieval_runtime_profile",
        fake_build_retrieval_runtime_profile,
    )

    def fake_select_initial_candidates(**kwargs):
        assert kwargs["candidate_ranker"] == "rrf_hybrid"
        assert kwargs["allow_empty_terms_fail_open"] is False
        return CandidateSelectionResult(
            requested_ranker="rrf_hybrid",
            selected_ranker="heuristic",
            min_score_used=1,
            fallback_reasons=["tiny_corpus"],
            candidates=[
                {
                    "path": "src/app.py",
                    "module": "src.app",
                    "language": "python",
                    "score": 3.0,
                }
            ],
        )

    monkeypatch.setattr("ace_lite.plan_quick.select_initial_candidates", fake_select_initial_candidates)

    result = build_plan_quick(
        query="auth token",
        root=tmp_path,
        languages="python",
        top_k_files=3,
        repomap_top_k=8,
        candidate_ranker="rrf_hybrid",
    )

    assert result["ranking_source"] == "ranker"
    assert result["candidate_ranker"] == "rrf_hybrid"
    assert result["candidate_ranker_selected"] == "heuristic"
    assert result["candidate_ranker_fallbacks"] == ["tiny_corpus"]
    assert result["candidate_min_score_used"] == 1
    assert result["candidate_files"] == ["src/app.py"]
    assert captured["profile_kwargs"] == {
        "candidate_ranker": "rrf_hybrid",
        "min_candidate_score": 1,
        "top_k_files": 8,
        "hybrid_fusion_mode": "linear",
        "hybrid_rrf_k": 60,
        "hybrid_weights": {},
        "index_hash": None,
        "allow_empty_terms_fail_open": False,
    }
    assert captured["corpus_size"] == 1


def test_build_plan_quick_includes_retrieval_policy_observability(tmp_path: Path) -> None:
    _write_file(tmp_path / "docs/architecture.md", "System architecture overview\n")

    result = build_plan_quick(
        query="how architecture works",
        root=tmp_path,
        languages="python,markdown",
        top_k_files=3,
        repomap_top_k=8,
    )

    assert result["retrieval_policy_profile"] == "doc_intent"
    assert result["retrieval_policy_observability"] == {
        "requested": "auto",
        "selected": "doc_intent",
        "source": "auto",
        "version": "v1",
        "embedding_enabled": True,
        "docs_enabled": True,
        "repomap_enabled": True,
        "graph_lookup_enabled": False,
        "chunk_semantic_rerank_enabled": True,
        "semantic_rerank_time_budget_ms": 120,
    }


def test_build_plan_quick_preserves_repomap_fallback_when_selection_is_empty(
    monkeypatch,
    tmp_path: Path,
) -> None:
    _write_file(tmp_path / "src/fallback.py", "def fallback_target():\n    return True\n")

    monkeypatch.setattr(
        "ace_lite.plan_quick.select_initial_candidates",
        lambda **kwargs: CandidateSelectionResult(
            requested_ranker="heuristic",
            selected_ranker="heuristic",
            min_score_used=1,
            fallback_reasons=[],
            candidates=[],
        ),
    )

    monkeypatch.setattr(
        "ace_lite.plan_quick.build_repo_map",
        lambda **kwargs: {
            "files": [
                {
                    "path": "src/fallback.py",
                    "module": "src.fallback",
                    "language": "python",
                    "score": 1.0,
                }
            ],
            "used_tokens": 17,
            "budget_tokens": 128,
            "ranking_profile": "graph",
        },
    )

    result = build_plan_quick(
        query="missing target",
        root=tmp_path,
        languages="python",
        top_k_files=3,
        repomap_top_k=8,
        budget_tokens=128,
    )

    assert result["ranking_source"] == "repomap"
    assert result["candidate_files"] == ["src/fallback.py"]
    assert result["repomap_used_tokens"] == 17
    assert result["repomap_budget_tokens"] == 128


def test_repomap_base_scoring_penalizes_generated_files(tmp_path: Path) -> None:
    business_symbols = "\n".join([f"def allow_{i}():\n    return {i}\n" for i in range(12)])
    _write_file(tmp_path / "internal/app/api/shutdown/allowlist.py", business_symbols)

    generated_symbols = "\n".join([f"def generated_{i}():\n    return {i}\n" for i in range(30)])
    _write_file(
        tmp_path / "pkg/contract/erc20_generated.py",
        "\n".join(["# Code generated by tool. DO NOT EDIT.", "", generated_symbols]),
    )

    index_payload = build_index(tmp_path, languages=["python"])
    ranked = rank_index_files(files=index_payload["files"], profile="heuristic")
    assert ranked
    assert ranked[0]["path"] == "internal/app/api/shutdown/allowlist.py"
